<?php
return [
  'ADMIN_ROLE_ID' => 1,
  'USER_ROLE_ID' => 2,
  'CUSTOMER_ROLE_ID' => 3,
  'SUCCESSFUL_FLAG' => 'Delete success!',
  'UNSUCCESSFUL_FLAG' => 'Delete unsuccess!',
  'ACCOUNTS_PER_PAGES' => 21,
  'MALE_GENDER' => 1,
  'FEMALE_GENDER' => 0,
  'LIMIT_STRING_DESCRIPTION_75' => 75,
  'TEN_RECORDS' => 10,
  'FEMALE_GENDER' => 0,
  'MALE_GENDER' => 1,
  'IMAGE_WIDTH' => 200,
  'IMAGE_HEIGHT' => 200,
  'DATE_DMY_FORMAT' => 'd/m/Y',
  'DATE_DMY_FORMAT_DATE_PICKER' => 'DD/MM/YYYY',
  'DATE_YMD_FORMAT' => 'Y-m-d',
  'IS_ON_SALE_YES'=> 'Yes',
  'IS_ON_SALE_NO'=> 'No',
  'ON_SALE' => 1,
  'OFF_SALE' => 0,
  'TOP_4' => 4,
  'TOP_5' => 5,
  'ONE_HUNDRED' => 100,
  'SELECT_FIVE' => 5,
  'SELECT_TEN' => 10,
];
